import type { Metadata } from "next";
import localFont from "next/font/local";
import { AuthProvider } from "@/contexts/auth-context";
import { LikesProvider } from "@/contexts/like-context";
import { ConditionalYouTubeProvider } from "@/components/conditional-youtube-provider";
import { AudioPlayerWrapper } from "@/components/audio-player-wrapper";
import "./globals.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<AuthProvider>
					<LikesProvider>
						<ConditionalYouTubeProvider>
							{children}
							<AudioPlayerWrapper />
						</ConditionalYouTubeProvider>
					</LikesProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
