services:
  curricurum_db:
    container_name: practice_mysql
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    tty: true
    ports:
      - 3308:3306
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - type: volume
        source: curriculum_mysql
        target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d

  mail:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp

volumes:
  curriculum_mysql:
    name: practice_mysql
  maildir: {}