// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Block struct {
	ID            string    `json:"id"`
	BlockedByID   string    `json:"blocked_by_id"`
	BlockedUserID string    `json:"blocked_user_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type Dm struct {
	ID         string    `json:"id"`
	SenderID   string    `json:"sender_id"`
	ReceiverID string    `json:"receiver_id"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
}

type Follow struct {
	ID          string    `json:"id"`
	FollowerID  string    `json:"follower_id"`
	FollowingID string    `json:"following_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Like struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TweetID   string    `json:"tweet_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Notification struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Type      string    `json:"type"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
	IsRead    bool      `json:"is_read"`
}

type Profile struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Bio       sql.NullString `json:"bio"`
	Location  sql.NullString `json:"location"`
	Website   sql.NullString `json:"website"`
	IsPrivate bool           `json:"is_private"`
}

type Reply struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TweetID   string    `json:"tweet_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type Retweet struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TweetID   string    `json:"tweet_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Tweet struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	IsDeleted bool      `json:"is_deleted"`
}

type User struct {
	ID        string         `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	CreatedAt time.Time      `json:"created_at"`
	Status    sql.NullString `json:"status"`
}
