// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateBlock(ctx context.Context, arg CreateBlockParams) (sql.Result, error)
	CreateDM(ctx context.Context, arg CreateDMParams) (sql.Result, error)
	CreateFollow(ctx context.Context, arg CreateFollowParams) (sql.Result, error)
	CreateLike(ctx context.Context, arg CreateLikeParams) (sql.Result, error)
	CreateReply(ctx context.Context, arg CreateReplyParams) (sql.Result, error)
	CreateRetweet(ctx context.Context, arg CreateRetweetParams) (sql.Result, error)
	CreateTweet(ctx context.Context, arg CreateTweetParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteBlock(ctx context.Context, arg DeleteBlockParams) error
	DeleteFollow(ctx context.Context, arg DeleteFollowParams) error
	DeleteLike(ctx context.Context, id string) error
	DeleteRetweet(ctx context.Context, id string) error
	DeleteTweet(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetProfile(ctx context.Context, userID string) (Profile, error)
	GetTweet(ctx context.Context, id string) (Tweet, error)
	GetUser(ctx context.Context, id string) (User, error)
	ListDMs(ctx context.Context, arg ListDMsParams) ([]Dm, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListReplies(ctx context.Context, tweetID string) ([]Reply, error)
	ListTweets(ctx context.Context, userID string) ([]Tweet, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkNotificationAsRead(ctx context.Context, id string) error
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
